# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# The command to output the secret: ansible-playbook -i inventory/hosts setup.yml --tags=create-secret-mastodon

- name: Run Mastodon 'bundle exec rails secret' command
  ansible.builtin.command:
    cmd: |-
      {{ devture_systemd_docker_base_host_command_docker }} run --rm
      {{ mastodon_web_container_image }}
      bundle exec rails secret
  register: mastodon_secret_result
  changed_when: mastodon_secret_result.rc == 0

- name: Extract SECRET_KEY_BASE for Mastodon
  ansible.builtin.set_fact:
    mastodon_secret_key_base: "{{ mastodon_secret_result.stdout }}"

- name: Inject a message about the generated SECRET_KEY_BASE for Mastodon
  # Add a empty line under the message for readability
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Add the line below for the secret key base to your vars.yml file:

          mastodon_environment_variables_secret_key_base: " + mastodon_secret_key_base + "

          "
        ]
      }}
