# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Mastodon paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ mastodon_uid }}"
    group: "{{ mastodon_gid }}"
  with_items:
    - "{{ mastodon_base_path }}"
    - "{{ mastodon_data_path }}"
    - "{{ mastodon_sidekiq_base_path }}"
    - "{{ mastodon_streaming_base_path }}"
    - "{{ mastodon_web_base_path }}"

- name: Ensure Mastodon support files installed
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0640"
    owner: "{{ mastodon_uid }}"
    group: "{{ mastodon_gid }}"
  with_items:
    - { src: "{{ role_path }}/templates/env.j2", dest: "{{ mastodon_base_path }}/env" }
    - { src: "{{ role_path }}/templates/labels_sidekiq.j2", dest: "{{ mastodon_sidekiq_base_path }}/labels" }
    - { src: "{{ role_path }}/templates/labels_streaming.j2", dest: "{{ mastodon_streaming_base_path }}/labels" }
    - { src: "{{ role_path }}/templates/labels_web.j2", dest: "{{ mastodon_web_base_path }}/labels" }
  register: mastodon_support_files_result

- name: Ensure Mastodon container images are pulled
  community.docker.docker_image:
    name: "{{ item }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
  with_items:
    - "{{ mastodon_sidekiq_container_image }}"
    - "{{ mastodon_streaming_container_image }}"
    - "{{ mastodon_web_container_image }}"
  register: mastodon_container_images_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: mastodon_container_images_pull_result is not failed

- name: Ensure Mastodon container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ mastodon_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: mastodon_network_creation_result

- name: Ensure Mastodon container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ mastodon_container_network }}
  register: mastodon_network_creation_result
  changed_when: mastodon_network_creation_result.rc == 0
  failed_when: mastodon_network_creation_result.rc != 0 and 'already exists' not in mastodon_network_creation_result.stderr

- name: Ensure Mastodon systemd services are present
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: "{{ role_path }}/templates/systemd/mastodon-sidekiq.service.j2"
      dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ mastodon_sidekiq_identifier }}.service"
    - src: "{{ role_path }}/templates/systemd/mastodon-streaming.service.j2"
      dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ mastodon_streaming_identifier }}.service"
    - src: "{{ role_path }}/templates/systemd/mastodon-web.service.j2"
      dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ mastodon_web_identifier }}.service"
  register: mastodon_systemd_services_result

- name: Determine whether Mastodon needs a restart
  ansible.builtin.set_fact:
    mastodon_restart_necessary: >-
      {{
        mastodon_support_files_result.changed | default(false)
        or mastodon_systemd_services_result.changed | default(false)
        or mastodon_container_images_pull_result.changed | default(false)
      }}
