# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Mastodon installation tasks
  when: mastodon_enabled | bool
  tags:
    - setup-all
    - setup-mastodon
    - install-all
    - install-mastodon
  block:
    - name: Validate Mastodon configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Mastodon
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Mastodon secret generation command tasks
  when: mastodon_enabled | bool
  tags:
    - create-secrets-all-mastodon
    - create-secret-mastodon
  block:
    - name: Run Mastodon 'bundle exec rails secret' to generate secrets
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_secret.yml"

- name: Perform Mastodon encryption secrets generation command tasks
  when: mastodon_enabled | bool
  tags:
    - create-secrets-all-mastodon
    - create-secrets-encryption-mastodon
  block:
    - name: Run Mastodon 'bin/rails db:encryption:init' to generate encryption secrets
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_secrets_encryption.yml"

- name: Perform Mastodon webpush keys generation command tasks
  when: mastodon_enabled | bool
  tags:
    - create-secrets-all-mastodon
    - create-secrets-webpush-mastodon
  block:
    - name: Run Mastodon 'bundle exec rails mastodon:webpush:generate_vapid_key' to generate web push keys
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_secrets_webpush.yml"

- name: Perform tasks to add users automatically to Mastodon
  when: mastodon_enabled | bool
  tags:
    - ensure-mastodon-users-created
    - ensure-users-created
  block:
    - name: Add users to Mastodon automatically
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_users_auto.yml"

- name: Perform tasks to add users manually to Mastodon
  when: mastodon_enabled | bool
  tags:
    - create-user-mastodon
    - create-owner-mastodon
    - create-admin-mastodon
    - create-moderator-mastodon
  block:
    - name: Add users to Mastodon manually
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/create_user_manual.yml"

- name: Perform Mastodon uninstallation tasks
  when: not mastodon_enabled | bool
  tags:
    - setup-all
    - setup-mastodon
  block:
    - name: Uninstall Mastodon
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
