# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of HedgeDoc systemd service
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: hedgedoc_service_stat

- name: Uninstall HedgeDoc systemd service
  when: hedgedoc_service_stat.stat.exists | bool
  block:
    - name: Ensure HedgeDoc systemd service is stopped
      ansible.builtin.service:
        name: "{{ item.service }}"
        state: stopped
        daemon_reload: true

    - name: Ensure HedgeDoc service does not exist
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: absent
