# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# The command to output the web push keys: ansible-playbook -i inventory/hosts setup.yml --tags=secrets-webpush-mastodon

- name: Run Mastodon 'bundle exec rails mastodon:webpush:generate_vapid_key' command
  ansible.builtin.command:
    cmd: |-
      {{ devture_systemd_docker_base_host_command_docker }} run --rm
      {{ mastodon_web_container_image }}
      bundle exec rails mastodon:webpush:generate_vapid_key
  register: mastodon_secrets_webpush_result
  changed_when: mastodon_secrets_webpush_result.rc == 0

- name: Extract VAPID_PRIVATE_KEY
  ansible.builtin.set_fact:
    mastodon_vapid_private_key: "{{ mastodon_secrets_webpush_result.stdout | regex_search('VAPID_PRIVATE_KEY=([^\\n]+)') | regex_replace('VAPID_PRIVATE_KEY=', '') }}"

- name: Extract VAPID_PUBLIC_KEY
  ansible.builtin.set_fact:
    mastodon_vapid_public_key: "{{ mastodon_secrets_webpush_result.stdout | regex_search('VAPID_PUBLIC_KEY=([^\\n]+)') | regex_replace('VAPID_PUBLIC_KEY=', '') }}"

# `devture_playbook_runtime_messages_list` is used as it conveniently respects line breaks.
- name: Show the webpush keys for Mastodon
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Set the values below to the variables for web push:

          - `" + mastodon_vapid_private_key + "` to `mastodon_environment_variables_vapid_private_key`
          - `" + mastodon_vapid_public_key + "` to `mastodon_environment_variables_vapid_public_key`"
        ]
      }}
